[package]
name = "lnconcinnity/ignition"
version = "2.2.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A True OOP & Reactive State DI Framework for Roblox"
license = "MIT"
repository = "https://github.com/lnconc/Ignition"
authors = ["lnconcinnity"]
homepage = "https://lnconc.github.io/Ignition/"
[dependencies]