[package]
name = "lnconc/ignition"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A True OOP & Reactive State DI Framework for Roblox"
license = "MIT"
authors = ["lnconcinnity"]
